### PR TITLE
Update timeInterval to Double format and delete semicolon

### PR DESCRIPTION
**Pull request by lamtrinhdev**
### Summary:

+ Correct using Double type for using timeIntervalSince1970 (At the document at https://developer.apple.com/documentation/foundation/timeinterval ).
+ Remove semicolon.

### Modifications:

+ Sources/AppStoreServerLibrary/ChainVerifier.swift
+ Tests/AppStoreServerLibraryTests/AppStoreServerAPIClientTests.swift
+ Tests/AppStoreServerLibraryTests/SignedDataVerifierTests.swift
+ Tests/AppStoreServerLibraryTests/TestingUtility.swift

### Result:

+ Correct timeInterval data type.
+ Remove semicolon with the Swift language.

### CODE REVIEW

**Comment by alexanderjordanbaker** [comment]
@lamtrinhdev What is the purpose or problem this PR looks to solve?

**Comment by lamtrinhdev** [comment]
Dear @alexanderjordanbaker ,

- Correct using timeInterval with Double format for input param.
- Swift language does not use semicolon for the end of line. (https://docs.swift.org/swift-book/documentation/the-swift-programming-language/thebasics/#Semicolons). I would like to correct that with following the standard.

Thanks,
Lam

**Comment by alexanderjordanbaker** [comment]
@lamtrinhdev 
> Correct using timeInterval with Double format for input param.

Type conversion automatically converts from the input into a Double, why is .0 needed here for the unit test?
> Swift language does not use semicolon for the end of line. 

Quoting the linked docs
`although you can do so if you wish.`
Is there a specific reason you wish to remove these semicolons?

**Comment by lamtrinhdev** [comment]
Dear @alexanderjordanbaker ,

I would like to make the code more clear because some place have semicolon other do not. It is the same with timeInterval some place have .0 and other do not.

That is my idea.

Thank you for your feedback. I will close this PR.

Thanks,
Lam

**Pull request closed without merging**
